### ISSUE TITLE
CRUD for Roles

### ISSUE THREAD

**Issue by HarryPi** [Quantium-Nonsense/ProjectOmega#18]
Allow CRUD request operations for User Roles ( This should be limited )

@travelingdeveloper12  Please review

**Comment by ka5110** [comment]
With the current back-end structure in mind, roles are assigned to users and roles would have fixed permissions. If that's the case we wouldn't need a delete role API. We would only need to update the roles with new permissions (e.g. for new features). Do we need to delete roles?

**Comment by ka5110** [comment]
With reference to above, do you think we need in the future to be able to customize roles (add extra permissions to a specific user?) or would fixed roles be enough. 

Below is our API List, please check and review **request parameters. 
 
[**New Microsoft Excel Worksheet.xlsx](https://github.com/Quantium-Nonsense/ProjectOmega/files/4201025/New.Microsoft.Excel.Worksheet.xlsx)

P.S: Our Base URL convention will be as follows: http:/localhost:8080/v1/api

**Comment by HarryPi** [comment]
Yes that is possible but that does imply we should keep a role that has no permissions.

**Comment by travelingdeveloper12** [comment]
CRUD APIs for Roles have been created. The APIs would be visible in PULL request #78
