### ISSUE TITLE
CRUD for Customer Data

### ISSUE THREAD

**Issue by HarryPi** [Quantium-Nonsense/ProjectOmega#20]
This was on the Wiki but i do not understand what it is.

@markscamilleri  Can you review this or tell me what it is supposed to be for?

**Comment by markscamilleri** [comment]
User Story:
-----------

Given that I am a user with the "Manage Customers" permission
And I am on the admin client
I want to be able to view, create, update and delete customer data

Details:
---------
This task includes the following:
   1. Table View listing Customers (Name, Surname, Company, Email and Contact Number) with edit/delete buttons
   2. Customer View listing all details of this customer (Could include address, description, previous orders)
   3. Form to create/edit customers,
   4. Delete Dialog asking to confirm the action.
 
The end result would be something similar to a contacts list. But Task #11 requires another functionality to be added here.

**Comment by HarryPi** [comment]
Alright makes sense thanks for clearing this up will mark is as an enhancement then

**Comment by HarryPi** [comment]
Done in #85
