### ISSUE TITLE
Allow basic product handling

### ISSUE THREAD

**Issue by HarryPi** [Quantium-Nonsense/ProjectOmega#3]
Client should allow for CRUD operations for a basic item

A basic item should hold at least the following fields
- Title
- Description
- Category
- Price

**Comment by markscamilleri** [comment]
User Story:
------------

Given that I am a user
And I have the "Product Management" permission
I want to be able to create, update, view and delete products.

Details:
---------
This task has the following sub-tasks:
   1. Design and develop the Products list page
   2. Design and develop the Product detail page
   3. Design and develop the Edit Product page
   4. Dialog box for deletion (to confirm deletion)
