### ISSUE TITLE
Should we plan to support I18n?

### ISSUE THREAD

**Issue by markscamilleri** [Quantium-Nonsense/ProjectOmega#33]
Since the first client is based in a country with multiple official languages, this set me thinking about internationalization and localization. Mainly:

   1. Translation of text/labels on the admin and rep client
   2. Support for different language inputs for the same product
   3. RTL support.

What do you guys think?

This is tagged as a question so we can discuss here (and so I won't forget to bring it up) but it is not a task (yet)

**Comment by HarryPi** [comment]
It should as we aim to target any company but possibly on a later phase
I am pretty sure if we get the main structure down this wont be to hard
