### ISSUE TITLE
Create Primary Layout

### ISSUE THREAD

**Issue by markscamilleri** [Quantium-Nonsense/ProjectOmega#44]
Each page will have the same layout as outlined in the image attached. This layout should contain:
 - Menu
 - Header bar
 - Footer

Diagram below by @DominikWas 
![scan_ms2109_2020-03-02-11-51-36](https://user-images.githubusercontent.com/1659973/75674101-4ca80000-5c7c-11ea-80d5-e1b3326f2b57.jpeg)

**Comment by DominikWas** [comment]
Completed under commit fd66e99, pull request opened

**Comment by markscamilleri** [comment]
This was closed in #46
