### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by HarryPi** [Quantium-Nonsense/ProjectOmega#5]
Client should authenticate each user and ensure each user views the view corresponding to their company

**Comment by markscamilleri** [comment]
Details:
----------

Following the login screen in #34 it's time to connect the frontend to the backend. The JWT token returned by the backend should be used to determine whether the user has permissions to view specific screens.

Depends on #22

**Comment by markscamilleri** [comment]
Closed but needs to be connected to the backend
