### ISSUE TITLE
Order management

### ISSUE THREAD

**Issue by HarryPi** [Quantium-Nonsense/ProjectOmega#8]
The client should be able to preview orders placed from the rep client and if needed amend or delete them.

~~Optional - Create new order as well~~ Moved to phase 2 #12

**Comment by HarryPi** [comment]
@markscamilleri  Please review the optional line here not sure if necessary

**Comment by markscamilleri** [comment]
I think it's best we leave Create New Order for Phase 2

**Comment by HarryPi** [comment]
Thanks i have created a new issue and have marked it as optional. In addition i mentioned this should be a phase 2 task and should be moved from optional to normal at the appropriate time.

**Comment by markscamilleri** [comment]
User Story:
------------

Give that I have access to the admin client
And I have the "View Orders" permission
I want to see the last orders placed and their status.

Give that I have access to the admin client
And I have the "Manage Orders" permission
I want to be able to edit or cancel orders.


Details:
---------
This task requires the design and development of:
  1. Orders view (list of orders)
  2. Order detail view
  3. Order editing form
  4. Cancel order confirmation dialog
