### ISSUE TITLE
Re-usable Searchbar

### ISSUE THREAD

**Issue by DominikWas** [Quantium-Nonsense/ProjectOmega#86]
Add in a re-usable searchbar that can be used across the admin frontend
* Structural directive design (hopefully)
* Design for mat-tables

**Comment by HarryPi** [comment]
@markscamilleri, @DominikWas 
>Structural directive design (hopefully)
 Having done some further research in this subject i no longer feel that a structural directive is appropriate for this task. I would suggest going for a re usable component instead for a couple of reasons; but without boring anyone into those the main important one is how more difficult this is to achieve with a structural directive. 
However, one of the components main functionality should still be to ensure that the component is only rendered with a MatTable thus not throwing random errors. ( this was the main reason a structural directive was prefered as it would directly be applied into it)

**Comment by markscamilleri** [comment]
So, would the best way be to have a general SearchBar component, or a SearchableTable component instead? 

Going for the former can still lead to the latter though

**Comment by HarryPi** [comment]
>So, would the best way be to have a general SearchBar component, or a SearchableTable component instead?

In reality programming principles dictate that we do a searchBar and then a SearchBarTable would extend it but a general search bar brings up a lot of questions, what is considered searchable HTML ? In reality if we have a mat table the filtering and reseting is handled by the Data Source object. If we have a simple HTML table the component should account for that. Then what if its a list of labels with ngFor?

I cant seem to find a generalisation without actually implementing this. Might give it a go today but open to ideas.

**Comment by DominikWas** [comment]
To save time: https://material.angular.io/components/table/overview under 'Filtering' is probably the way to go and ensure a mat table is used. The filtering for the mat-table searches through all the HTML (essential for record searching) and can be adjusted to column searches too. 

I think a separate search bar component could be made but that is only if it's absolutely necessary.  @HarryPi  @markscamilleri

**Comment by DominikWas** [comment]
I will try the above^

**Comment by DominikWas** [comment]
Completed search bar filter under 893998d on #62 - decided to add it under customer management branch

**Comment by HarryPi** [comment]
> Completed search bar filter under [893998d](https://github.com/Quantium-Nonsense/ProjectOmega/commit/893998d3f925bc56aba2aa2aa212b318d6d4f1ba) on #62 - decided to add it under customer management branch

Please be aware this is in no way re-usable what you are doing there is simply creating it for your own table as its in the customers component. For a component to be re-usable it needs to be in its own component.

As you will be unavailable until the 24th i have completed this tasks so we can have something see commit c2a5dc01a9680f028472769ebf47732d78486cb7
